### ISSUE TITLE
Using :rest as group name fails

### ISSUE THREAD

**Issue by ikitommi** [cgrand/seqexp#10]
This works as expected:

```clj
(se/exec
  (se/cat
    (se/as :x int?)
    (se/as :y int?)
    (se/as :rest2 (se/* string?)))
  [1 2 "kikka" "kukka"])
; {:rest (), :match (1 2 "kikka" "kukka"), :x (1), :y (2), :rest2 ("kikka" "kukka")}
```

Here, the `:rest` is empty (as it conflicts with the reserved key):

```clj
(se/exec
  (se/cat
    (se/as :x int?)
    (se/as :y int?)
    (se/as :rest (se/* string?)))
  [1 2 "kikka" "kukka"])
; {:rest (), :match (1 2 "kikka" "kukka"), :x (1), :y (2)}
```

, maybe the `:rest` should be namespaced to `:net.cgrand.seqexp/rest` or the matched groups should be under `:groups`, e.g.

```clj
{:rest (), 
 :match (1 2 "kikka" "kukka")
 :groups {:x (1), 
          :y (2)
          :rest ("kikka" "kukka")}}
```

**Comment by cgrand** [comment]
Too late for a breaking change.
However defining a `tommi-better-exec` is quite doable (all the `:rest` and `:match` "magic" occurs in `exec` and `exec` is rather straightforward).

**Comment by ikitommi** [comment]
thanks!
