### ISSUE TITLE
question: Regex protocol is private, why?

### ISSUE THREAD

**Issue by pbaille** [cgrand/seqexp#8]
Hello,

I'm playing with your really cool library, i like it very much, but i need to extend Regex, why do you prevent users from doing that?

Thank you

**Comment by cgrand** [comment]
Why do you need to extend it?
The rationale is that's something I don't want to commit to and be free to change it without having to worry about breaking someone else code.

**Comment by pbaille** [comment]
Hi,
I'm trying to build a "clojure.spec like" thing on top of seqexp.
I understand your concerns. 
Since the code base is so small, i've just copy and pasted it in my project for now.
Thank you for all
